name: Build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'app/**'
      - 'gradle/**'
      - '*.gradle'
      - '*.properties'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Set environments
        run: |
          echo "version=v$(grep versionName app/build.gradle | awk '{print $2}' | tr -d \")" >> $GITHUB_ENV
          echo "commit=$(echo ${{ github.sha }} | cut -c-7)" >> $GITHUB_ENV
          echo "repo=$(echo ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/})" >> $GITHUB_ENV

      - name: Build
        run: |
          ./gradlew clean assembleDebug --no-daemon --stacktrace
          cp -f app/build/outputs/apk/debug/app-debug.apk ${{ env.repo }}-${{ env.version }}.apk

      - name: Attest
        continue-on-error: true
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: ${{ env.repo }}-${{ env.version }}.apk

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ replace(replace(replace(env.repo, '\r', ''), '\n', ''), ' ', '-') }}-${{ replace(replace(env.version, '\r', ''), '\n', '') }}-${{ github.sha }}
          path: ${{ env.repo }}-${{ env.version }}.apk
